### ISSUE TITLE
Plugin details not working with newest version

### ISSUE THREAD

**Issue by stanislaw-patalewski** [GetResponse/GetresponseForPrestashop#1]
### Why Plugin Details is disabled? I have the latest release.

![image](https://user-images.githubusercontent.com/98430987/178713483-2cbccff2-a9cf-4a22-ba0b-f9b8de33f331.png)

**Comment by BartStep** [comment]
Hi, please contact us via GetResponse support: https://www.getresponse.com/features/support
(When it comes to the GetResponse platform itself, this form of contact should be your first choice.)
